export const PAYS = [
  'FRANCE', 'ALLEMAGNE', 'ESPAGNE', 'ITALIE', 'PORTUGAL', 'BELGIQUE',
  'SUISSE', 'AUTRICHE', 'POLOGNE', 'GRECE', 'NORVEGE', 'SUEDE',
  'DANEMARK', 'FINLANDE', 'IRLANDE', 'CROATIE', 'PAYS-BAS', 'TCHEQUE',
  'HONGRIE', 'ROUMANIE', 'BULGARIE', 'SERBIE', 'UKRAINE', 'MAROC',
  'ALGERIE', 'TUNISIE', 'EGYPTE', 'SENEGAL', 'CAMEROUN', 'MALI',
  'NIGER', 'CANADA', 'MEXIQUE', 'BRESIL', 'ARGENTINE', 'CHILI',
  'PEROU', 'COLOMBIE', 'VENEZUELA', 'EQUATEUR', 'BOLIVIE', 'CHINE',
  'JAPON', 'INDE', 'THAILANDE', 'VIETNAM', 'COREE', 'PAKISTAN',
  'IRAN', 'IRAK', 'TURQUIE', 'ISRAEL', 'LIBAN', 'JORDANIE',
  'AUSTRALIE', 'RUSSIE', 'MONGOLIE', 'KENYA', 'GHANA', 'ZAMBIE'
];

export const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ-'.split('');

export const COMMON_LETTERS = ['E', 'A', 'S', 'I', 'N', 'R', 'T', 'O', 'L', 'U'];

